version: '2'

services:
  jupyter:
    image: platipy/platipy:jupyter
    restart: "no"
    ports:
     - "8080:8080"
    volumes:
     - ../../..:/jpy
     - ../.gitconfig:/home/service/.gitconfig
     - ../.ssh:/root/.ssh

